
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PMS
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8899
